name: integrate dependencies - dev
run-name: Integrate Dependencies
on:
  workflow_dispatch:
    inputs:
      build_version:
        description: 'Build version to integrate'
        required: true
        default: 'latest'
      repository:
        description: 'Repository to integrate'
        required: true
        default: 'gha-scratch-pad1'
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Search for ${{ github.event.inputs.build_version }} in libs.version.toml
      run: |
        filename="gradle/libs.version.toml"
        man sed
        case "${{ github.event.inputs.repository }}" in
          "gha-scratch-pad1")
            sed -i -E 's/(gha1-chart\s*=\s*\")([^\"]+)(\")/\1${{ github.event.inputs.build_version }}\3/' "${filename}"
            ;;
          "gha-scratch-pad2")
            sed -i -E 's/(gha2-chart\s*=\s*\")([^\"]+)(\")/\1${{ github.event.inputs.build_version }}\3/' "${filename}"
            ;;
          *)
            echo "Repository ${{ github.event.inputs.repository }} not supported"
            exit 1
            ;;
        esac

    - name: Show changes
      run: |
          git diff
          git status