name: integrate dependencies - dev
run-name: Integrate Dependencies
on:
  repository_dispatch:
    types:
      - build-published
  workflow_dispatch:
    inputs:
      build_version:
        description: 'Build version to integrate'
        required: true
        default: 'latest'
      build_repository:
        description: 'Build repository to integrate'
        required: true
        default: 'gha-scratch-pad1'
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set Build Version
      id: build_summary
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "build_version=${{ github.event.inputs.build_version }}" >> $GITHUB_OUTPUT
          echo "build_repository=${{ github.event.inputs.build_repository }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          echo "build_version=${{ github.event.client_payload.build_version }}" >> $GITHUB_OUTPUT
          echo "build_repository=${{ github.event.client_payload.build_repository }}" >> $GITHUB_OUTPUT
        else
          echo "No input provided."
          exit 1
        fi

    - name: Replace '${{ steps.build_summary.outputs.build_repository }}' build version with '${{ steps.build_summary.outputs.build_version }}'
      run: |
        filename="gradle/libs.version.toml"
        case "${{ steps.build_summary.outputs.build_repository }}" in
          "gha-scratch-pad1")
            sed -i -E 's/(gha1-chart\s*=\s*\")([^\"]+)(\")/\1${{ steps.build_summary.outputs.build_version }}\3/' "${filename}"
            ;;
          "gha-scratch-pad2")
            sed -i -E 's/(gha2-chart\s*=\s*\")([^\"]+)(\")/\1${{ steps.build_summary.outputs.build_version }}\3/' "${filename}"
            ;;
          *)
            echo "Repository ${{ steps.build_summary.outputs.build_repository }} not supported"
            exit 1
            ;;
        esac

    - name: Show changes
      run: |
          git diff
          git status

    - name: Configure Git
      run: |
        git config --global user.name "rubel-ahammad"
        git config --global user.email "rubel.ahammad@gmail.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Automated changes on $(date)" || echo "No changes to commit."

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main